defaults:
  PLANT_CAP_MW: 20.0
  MIN_LOAD_PCT: 10.0
  MAX_LOAD_PCT: 100.0
  BREAK_EVEN_EUR_MWH: 50.0
  RAMP_LIMIT_MW: 2.0
  ALWAYS_ON: true

  MWH_PER_TON: 11.0
  MEOH_PRICE: 1000.0
  CO2_PRICE: 40.0
  CO2_INTENSITY: 1.375
  MAINT_PCT: 3.0
  SGA_PCT: 2.0
  INS_PCT: 1.0
  WATER_COST_T: 7.3
  OTHER_OPEX_T: 0.0

ui:
  logo: "logo.png"
  theme: "dark"

battery_defaults:
  enabled: false
  e_mwh: 10.0
  p_ch_mw: 5.0
  p_dis_mw: 5.0
  eff_ch: 0.95
  eff_dis: 0.95
  soc_min: 0.10
  soc_max: 0.90
  price_low: 30.0
  price_high: 90.0
  degradation_eur_per_mwh: 0.0
